name: CI

on:
  pull_request:
    paths:
      - 'recipes/**'
      - 'build.py'
      - '.github/workflows/all.yml'
  push:
    branches:
      - master
    paths:
      - 'recipes/**'
      - 'build.py'
      - '.github/workflows/all.yml'

env:
  CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
  REMOTES_MASTER: ${{ secrets.REMOTES_MASTER }}
  REMOTES_STAGING: ${{ secrets.REMOTES_STAGING }}
  REMOTES_UPLOAD_USER: ${{ secrets.REMOTES_UPLOAD_USER }}
  IS_PURE_C: true

jobs:
  ci:
    strategy:
      matrix:
        build: ['linux-gcc8', 'macos']
        include:
          - build: 'linux-gcc8'
            os: 'ubuntu-latest'
            archs: 'x86_64'
            compiler: 'gcc'
            compiler_version: '8'
            conanpath: 'trassir/lnvr'
            build_types: 'Release,Debug'
            docker_image: 'trassiross/conan-gcc8'
          - build: 'macos'
            os: 'macos-10.15'
            archs: 'x86_64'
            compiler: 'apple_clang'
            compiler_version: '11.0'
            conanpath: 'trassir/mac'
            build_types: 'Release'
            deployment-target: '10.14'
            xcode_version: '11.4'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure git
        run: git config --global core.autocrlf false
        shell: bash
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: sources
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Build and Optionally Upload
        uses: trassir/run-cpt@v0.2.2-trassir
        with:
          install: custom
          # TODO: replace when https://github.com/conan-io/conan-package-tools/issues/479 will be fixed upstream
          custom-package: git+https://github.com/trassir/conan-package-tools@fix-479-trassir
          work-dir: sources/
          build-script: build.py
          compiler: ${{ matrix.compiler }}
          compiler-versions: ${{ matrix.compiler_version }}
          docker-images: ${{ matrix.docker_image }}
        env:
          CONAN_TXT: ${{ matrix.conanpath }}/conanfile.txt
          CONAN_PROFILE: ${{ matrix.conanpath }}/conanprofile
          CONAN_BUILD_TYPES: ${{ matrix.build_types }}
          MACOSX_DEPLOYMENT_TARGET: ${{ matrix.deployment-target }}
          CONAN_VISUAL_RUNTIMES: ${{ matrix.vs_runtimes }}
          CONAN_ARCHS: ${{ matrix.archs }}
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer
