name: CI

on:
  pull_request:
    paths:
      - 'recipes/**'
      - 'trassir/**'
      - '*.py'
      - '.github/workflows/all.yml'
  push:
    branches:
      - master
    paths:
      - 'recipes/**'
      - 'trassir/**'
      - '*.py'
      - '.github/workflows/all.yml'

env:
  CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
  REMOTES_MASTER: ${{ secrets.REMOTES_MASTER }}
  REMOTES_STAGING: ${{ secrets.REMOTES_STAGING }}
  REMOTES_UPLOAD_USER: ${{ secrets.REMOTES_UPLOAD_USER }}
  IS_PURE_C: true

jobs:
  conan:
    strategy:
      matrix:
        build: ['windows-2019-release',
                'windows-2019-debug',
                'linux-gcc8-release',
                'linux-gcc8-debug',
                'macos-release'
                ]
        include:
          - build: 'windows-2019-release'
            os: 'windows-2019'
            compiler: 'vs'
            compiler_version: '16'
            vs_runtimes: 'MD,MT'
            conan_txt: 'trassir/win32-vc16/conanfile.txt'
            conan_profile: 'trassir/win32-vc16/conanprofile.release'
            build_types: 'Release'
          - build: 'windows-2019-debug'
            os: 'windows-2019'
            compiler: 'vs'
            compiler_version: '16'
            vs_runtimes: 'MD,MT'
            conan_txt: 'trassir/win32-vc16/conanfile.txt'
            conan_profile: 'trassir/win32-vc16/conanprofile.debug'
            build_types: 'Debug'
          - build: 'linux-gcc8-release'
            os: 'ubuntu-latest'
            archs: 'x86_64'
            compiler: 'gcc'
            compiler_version: '8'
            conan_txt: 'trassir/lnvr-gcc4.8/conanfile.txt'
            conan_profile: 'trassir/lnvr-gcc4.8/conanprofile'
            build_types: 'Release'
            docker_image: 'trassiross/conan-gcc8'
          - build: 'linux-gcc8-debug'
            os: 'ubuntu-latest'
            archs: 'x86_64'
            compiler: 'gcc'
            compiler_version: '8'
            conan_txt: 'trassir/lnvr-gcc4.8/conanfile.txt'
            conan_profile: 'trassir/lnvr-gcc4.8/conanprofile'
            build_types: 'Debug'
            docker_image: 'trassiross/conan-gcc8'
          - build: 'macos-release'
            os: 'macos-10.15'
            archs: 'x86_64'
            compiler: 'apple_clang'
            compiler_version: '11.0'
            conan_txt: 'trassir/mac-clang11/conanfile.txt'
            conan_profile: 'trassir/mac-clang11/conanprofile.release'
            build_types: 'Release'
            deployment-target: '10.14'
            xcode_version: '11.4'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure git
        run: git config --global core.autocrlf false
        shell: bash
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: sources
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Build and Optionally Upload
        uses: trassir/run-cpt@v0.2.2-trassir
        with:
          install: custom
          # TODO: replace when https://github.com/conan-io/conan-package-tools/issues/479 will be fixed upstream
          custom-package: git+https://github.com/trassir/conan-package-tools@fix-479-trassir
          work-dir: sources/
          build-script: build.py
          compiler: ${{ matrix.compiler }}
          compiler-versions: ${{ matrix.compiler_version }}
          docker-images: ${{ matrix.docker_image }}
        env:
          CONAN_TXT: ${{ matrix.conan_txt }}
          CONAN_PROFILE: ${{ matrix.conan_profile }}
          CONAN_BUILD_TYPES: ${{ matrix.build_types }}
          MACOSX_DEPLOYMENT_TARGET: ${{ matrix.deployment-target }}
          CONAN_VISUAL_RUNTIMES: ${{ matrix.vs_runtimes }}
          CONAN_ARCHS: ${{ matrix.archs }}
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer
